"""
server/grpc_server.py
gRPC transport layer for the ML Inference System.
Runs alongside the FastAPI server, reusing the same DynamicBatcher and InferenceEngine.

Start:
    python -m server.grpc_server       # standalone on port 50051
    # Or import and call start_grpc_server() inside the FastAPI startup event

Demonstrates:
    - gRPC vs HTTP transport tradeoffs
    - Binary serialization (protobuf) vs JSON overhead
    - Multiplexed HTTP/2 connections vs HTTP/1.1 keep-alive
"""

import asyncio
import time
import sys
from pathlib import Path
from concurrent import futures

import grpc

# Import generated stubs (generated by: python -m grpc_tools.protoc ...)
sys.path.insert(0, str(Path(__file__).parent))
import inference_pb2
import inference_pb2_grpc

from server.model import get_engine
from server.batching import DynamicBatcher

GRPC_PORT = 50051
_batcher: DynamicBatcher | None = None


def get_batcher() -> DynamicBatcher:
    global _batcher
    if _batcher is None:
        engine = get_engine()
        _batcher = DynamicBatcher(
            engine_generate_batch_fn=engine.generate_batch,
            max_batch_size=8,
            timeout_ms=20
        )
    return _batcher


class InferenceServicer(inference_pb2_grpc.InferenceServiceServicer):
    """
    gRPC servicer implementing the InferenceService.
    Routes through the same DynamicBatcher + KV-Cache backed InferenceEngine
    as the FastAPI HTTP endpoints — the transport layer is the only difference.
    """

    async def Generate(
        self,
        request: inference_pb2.GenerateRequest,
        context: grpc.aio.ServicerContext
    ) -> inference_pb2.GenerateResponse:
        batcher = get_batcher()
        try:
            result, latency = await batcher.process_request(
                request.prompt,
                request.max_new_tokens or 50
            )
            return inference_pb2.GenerateResponse(text=result, latency_ms=latency)
        except Exception as e:
            await context.abort(grpc.StatusCode.INTERNAL, str(e))

    async def BatchGenerate(
        self,
        request: inference_pb2.BatchGenerateRequest,
        context: grpc.aio.ServicerContext
    ) -> inference_pb2.BatchGenerateResponse:
        engine = get_engine()
        try:
            start = time.time()
            loop = asyncio.get_running_loop()
            results = await loop.run_in_executor(
                None,
                engine.generate_batch,
                list(request.prompts),
                request.max_new_tokens or 50
            )
            latency = (time.time() - start) * 1000
            return inference_pb2.BatchGenerateResponse(texts=results, latency_ms=latency)
        except Exception as e:
            await context.abort(grpc.StatusCode.INTERNAL, str(e))

    async def Health(
        self,
        request: inference_pb2.HealthRequest,
        context: grpc.aio.ServicerContext
    ) -> inference_pb2.HealthResponse:
        return inference_pb2.HealthResponse(status="ok", model_loaded=True)


async def serve(port: int = GRPC_PORT):
    """Start the async gRPC server."""
    batcher = get_batcher()
    batcher.start()

    server = grpc.aio.server()
    inference_pb2_grpc.add_InferenceServiceServicer_to_server(InferenceServicer(), server)
    server.add_insecure_port(f"[::]:{port}")

    print(f"[gRPC] Server starting on port {port}...")
    await server.start()
    print(f"[gRPC] Listening on port {port} — ready for requests")
    print(f"[gRPC] Transport: HTTP/2 + Protobuf (binary serialization)")

    await server.wait_for_termination()


if __name__ == "__main__":
    asyncio.run(serve())
