# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"9\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x02 \x01(\x05\"4\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x01\"?\n\x14\x42\x61tchGenerateRequest\x12\x0f\n\x07prompts\x18\x01 \x03(\t\x12\x16\n\x0emax_new_tokens\x18\x02 \x01(\x05\":\n\x15\x42\x61tchGenerateResponse\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x01\"\x0f\n\rHealthRequest\"6\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x02 \x01(\x08\x32\xea\x01\n\x10InferenceService\x12\x43\n\x08Generate\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse\x12R\n\rBatchGenerate\x12\x1f.inference.BatchGenerateRequest\x1a .inference.BatchGenerateResponse\x12=\n\x06Health\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=30
  _globals['_GENERATEREQUEST']._serialized_end=87
  _globals['_GENERATERESPONSE']._serialized_start=89
  _globals['_GENERATERESPONSE']._serialized_end=141
  _globals['_BATCHGENERATEREQUEST']._serialized_start=143
  _globals['_BATCHGENERATEREQUEST']._serialized_end=206
  _globals['_BATCHGENERATERESPONSE']._serialized_start=208
  _globals['_BATCHGENERATERESPONSE']._serialized_end=266
  _globals['_HEALTHREQUEST']._serialized_start=268
  _globals['_HEALTHREQUEST']._serialized_end=283
  _globals['_HEALTHRESPONSE']._serialized_start=285
  _globals['_HEALTHRESPONSE']._serialized_end=339
  _globals['_INFERENCESERVICE']._serialized_start=342
  _globals['_INFERENCESERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
